version: '3.8'
services:
  postgres:
    image: postgres
    container_name: hnlrate-postgres
    environment:
      POSTGRES_DB: hnlrate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"