import { StyleSheet } from 'react-native';

export const screen = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#000000' },
  content: { padding: 20, paddingBottom: 48 },
  centered: {
    flex: 1,
    backgroundColor: '#000000',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#1A1A1A',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  errorText: { color: '#666666', fontSize: 16 },

  hero: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 20,
  },
  crest: { width: 52, height: 52, flexShrink: 0 },
  crestPlaceholder: {
    width: 52,
    height: 52,
    borderRadius: 10,
    backgroundColor: '#1A1A1A',
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
  },
  crestInitials: { fontSize: 14, fontWeight: '800', color: '#444444' },
  heroText: { flex: 1 },
  clubName: { fontSize: 18, fontWeight: '800', color: '#FFFFFF' },
  clubMeta: { fontSize: 12, color: '#555555', marginTop: 2 },
  favIcon: { padding: 6 },
  btnDisabled: { opacity: 0.5 },

  filterRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 18,
  },
  filterTab: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: '#111111',
    borderWidth: 1,
    borderColor: '#1E1E1E',
    alignItems: 'center',
  },
  filterTabActive: {
    backgroundColor: '#1A0000',
    borderColor: '#CC0000',
  },
  filterTabText: { fontSize: 13, fontWeight: '700', color: '#555555' },
  filterTabTextActive: { color: '#CC0000' },

  empty: { alignItems: 'center', paddingTop: 32 },
  emptyText: { color: '#333333', fontSize: 14 },
});

export const featCard = StyleSheet.create({
  card: {
    backgroundColor: '#0D0000',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#3A0000',
    padding: 16,
    marginBottom: 12,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  nextBadge: {
    backgroundColor: '#CC0000',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 5,
  },
  nextText: {
    fontSize: 10,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: 0.8,
  },
  roundText: { fontSize: 12, color: '#555555', fontWeight: '600' },
  teams: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  teamBlock: { flex: 1, alignItems: 'center', gap: 6 },
  logo: { width: 44, height: 44 },
  logoPlaceholder: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: '#1A1A1A',
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoInitials: { fontSize: 11, fontWeight: '700', color: '#444444' },
  clubName: {
    fontSize: 13,
    fontWeight: '600',
    color: '#CCCCCC',
    textAlign: 'center',
    maxWidth: 120,
  },
  homeAway: {
    fontSize: 10,
    color: '#444444',
    fontWeight: '600',
    letterSpacing: 0.8,
  },
  vsBlock: { width: 50, alignItems: 'center' },
  vs: { fontSize: 16, fontWeight: '800', color: '#333333' },
  footer: {
    gap: 5,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#1A0000',
  },
  footerRow: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  footerText: { fontSize: 12, color: '#666666' },
});

export const mc = StyleSheet.create({
  card: {
    backgroundColor: '#111111',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#1E1E1E',
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 6,
  },
  row: { flexDirection: 'row', alignItems: 'center' },
  teamSide: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 6 },
  teamSideRight: { justifyContent: 'flex-end' },
  logo: { width: 26, height: 26 },
  logoPlaceholder: {
    width: 26,
    height: 26,
    borderRadius: 5,
    backgroundColor: '#1A1A1A',
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoInitials: { fontSize: 8, fontWeight: '700', color: '#444444' },
  tla: { fontSize: 12, fontWeight: '700', color: '#CCCCCC', flexShrink: 1 },
  centre: { width: 64, alignItems: 'center' },
  score: { fontSize: 16, fontWeight: '800', color: '#FFFFFF' },
  scoreWin: { color: '#22C55E' },
  scoreLoss: { color: '#CC0000' },
  scoreDraw: { color: '#F59E0B' },
  vs: { fontSize: 13, fontWeight: '700', color: '#333333' },
  meta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 6,
  },
  metaText: { fontSize: 11, color: '#444444' },
  badge: {
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 4,
    backgroundColor: '#1A1A1A',
  },
  badgeWin: { backgroundColor: '#052E16' },
  badgeLoss: { backgroundColor: '#1A0000' },
  badgeDraw: { backgroundColor: '#1C1200' },
  badgeText: { fontSize: 10, fontWeight: '800', color: '#FFFFFF' },
});
