import { T } from '@/constants/theme';
import { StyleSheet } from 'react-native';

export const rm = StyleSheet.create({
  container: { flex: 1, backgroundColor: T.bg },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 16,
    paddingTop: 20,
  },
  closeBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: T.surface,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: T.hairline,
  },
  progress: { flex: 1, flexDirection: 'row', gap: 4 },
  progressBar: {
    flex: 1,
    height: 3,
    borderRadius: 2,
    backgroundColor: T.hairlineStrong,
  },
  progressBarActive: { backgroundColor: T.red },
  stepCount: {
    fontSize: 11,
    color: T.textFaint,
    fontWeight: '600',
    minWidth: 24,
    textAlign: 'right',
  },

  scroll: { paddingHorizontal: 20, paddingBottom: 20 },

  peekOuter: {
    height: 18,
    borderRadius: 18,
    marginHorizontal: 16,
    backgroundColor: T.surfaceHi,
    borderWidth: 1,
    borderColor: T.hairline,
    marginBottom: -12,
    opacity: 0.5,
  },
  peekInner: {
    height: 18,
    borderRadius: 18,
    marginHorizontal: 8,
    backgroundColor: T.surfaceHi,
    borderWidth: 1,
    borderColor: T.hairline,
    marginBottom: -12,
    opacity: 0.75,
  },
  card: {
    backgroundColor: T.surface,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: T.hairlineStrong,
    padding: 22,
    shadowColor: '#000',
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 10,
    zIndex: 10,
  },

  stepLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: T.textFaint,
    letterSpacing: 1,
    marginBottom: 8,
  },
  cardTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: T.text,
    letterSpacing: -0.8,
    lineHeight: 30,
    marginBottom: 6,
  },
  cardSub: { fontSize: 13, color: T.textDim, marginBottom: 20 },

  bigNumWrap: { alignItems: 'center', marginBottom: 20 },
  bigNum: {
    fontSize: 88,
    fontWeight: '900',
    letterSpacing: -4,
    lineHeight: 92,
  },
  bigNumLabel: {
    fontSize: 13,
    color: T.textFaint,
    fontWeight: '600',
    marginTop: 2,
  },

  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: {
    width: '17%',
    aspectRatio: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: T.hairline,
    justifyContent: 'center',
    alignItems: 'center',
    flexGrow: 1,
  },
  chipText: { fontSize: 17, fontWeight: '800', letterSpacing: -0.3 },

  commentInput: {
    backgroundColor: T.bg,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: T.hairlineStrong,
    padding: 14,
    color: T.text,
    fontSize: 14,
    lineHeight: 20,
    minHeight: 120,
    marginTop: 4,
  },
  commentCount: {
    fontSize: 11,
    color: T.textFaint,
    textAlign: 'right',
    marginTop: 6,
  },

  summaryGrid: { flexDirection: 'row', gap: 8, marginTop: 16 },

  actionCard: {
    marginTop: 12,
    padding: 14,
    borderRadius: 14,
    backgroundColor: T.surfaceHi,
    borderWidth: 1,
    borderColor: T.hairlineStrong,
    gap: 12,
  },
  actionHeader: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  actionNum: {
    width: 30,
    height: 30,
    borderRadius: 7,
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
  },
  actionNumHome: { backgroundColor: '#FFFFFF' },
  actionNumAway: { backgroundColor: '#CC0000' },
  actionNumText: { fontSize: 12, fontWeight: '800', color: '#111' },
  actionName: { fontSize: 14, fontWeight: '700', color: T.text },
  actionClub: { fontSize: 11, color: T.textFaint, marginTop: 1 },
  actionBtns: { flexDirection: 'row', gap: 8 },
  actionBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: T.hairline,
    backgroundColor: T.bg,
    alignItems: 'center',
  },
  actionBtnBest: { borderColor: T.win, backgroundColor: 'rgba(39,195,111,0.08)' },
  actionBtnWorst: { borderColor: T.loss, backgroundColor: 'rgba(229,72,77,0.08)' },
  actionBtnText: { fontSize: 13, fontWeight: '700', color: T.textDim },
  actionComment: {
    height: 36,
    backgroundColor: T.bg,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: T.hairline,
    paddingHorizontal: 10,
    fontSize: 12,
    color: T.text,
  },

  commentPreview: {
    marginTop: 14,
    padding: 12,
    borderRadius: 12,
    backgroundColor: T.bg,
    borderWidth: 1,
    borderColor: T.hairlineStrong,
  },
  commentPreviewLabel: {
    fontSize: 9,
    fontWeight: '700',
    color: T.textFaint,
    letterSpacing: 0.6,
    marginBottom: 6,
  },
  commentPreviewText: { fontSize: 13, color: T.textDim, lineHeight: 18 },

  footer: {
    flexDirection: 'row',
    gap: 10,
    padding: 16,
    paddingBottom: 32,
    borderTopWidth: 1,
    borderTopColor: T.hairline,
  },
  skipBtn: {
    flex: 1,
    height: 52,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: T.hairlineStrong,
  },
  skipText: { fontSize: 14, fontWeight: '600', color: T.text },
  nextBtn: {
    flex: 2,
    height: 52,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: T.red,
    shadowColor: T.red,
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 6,
  },
  nextText: { fontSize: 16, fontWeight: '700', color: '#fff' },
});
